config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'users' => "user_lists#index", as: 'users'
  devise_for :users, path_names: {current_user: 'me'}
  get 'users/:id' => "user_lists#show", as: 'user'

  resources :relationships, only: [:create, :destroy]
  resources :skills, only: [:create, :destroy]

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :adder, class_name: "User"
  belongs_to :skill
  validates :user_id, presence: true, uniqueness: {scope: [:adder_id, :skill_id]}
  validates :adder_id, presence: true
  validates :skill_id, presence: true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :relationships, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  extend OrderAsSpecified
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: { maximum: 50 }
  has_many :has_skill, class_name: "Relationship", dependent: :destroy
  has_many :add_skill, class_name: "Relationship", foreign_key: "adder_id", dependent: :destroy
  has_many :skills, through: :has_skill



  def plus_one(other_user, ability)
    _add_skill = add_skill.new(user_id: other_user.id, skill_id: ability.id)
    _add_skill.save
  end

  def plussed?(other_user, ability)
    add_skill.exists?(user_id: other_user.id, skill_id: ability.id)
  end

  def delete_skill(ability)
    abilities = has_skill.where(skill_id: ability.id).find_each{ |a|
    	a.destroy
    }
  end

  def skill_having?(ability)
  	skills.include?(ability)
  end

  def skills_list
    ordered_counts = skills.group('skills.id').order('count_all desc').count
    [skills.group(:id).order_as_specified(id: ordered_counts.keys), ordered_counts]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # deviceのコントローラーのときに、下記のメソッドを呼ぶ
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/me_controller.rb
class MeController < Devise::RegistrationsController
  before_action :authenticate_user!
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user,   only: :destroy
  def create
  	user = User.find(params[:user_id])
  	ability = Skill.find(params[:skill_id])
    if current_user.plus_one(user, ability)
      flash[:notice] = ability.name + " に +1 しました"
    else
      flash[:alert] = ability.name + " への +1 に失敗しました"
    end
    redirect_to user
  end

  def destroy
    skill = Skill.find(@relation.skill_id)
    @relation.destroy
    flash[:notice] = skill.name+" を -1 しました"
    redirect_to user_path id: @relation.user_id
  end

private
  def correct_user
    @relation = current_user.add_skill.find_by(id: params[:id])
    redirect_to root_path if @relation.nil?
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate_user!
  def create
    added_user = User.find(params[:added_id])

    if Skill.exists?(name: skill_params[:name])
      @skill = Skill.find_by(name: skill_params[:name])
    else
      @skill = Skill.new(skill_params)
      if !@skill.save
        flash[:alert] = "新規スキルの作成に失敗しました"
        return redirect_to added_user
      end
    end

    if current_user.plus_one(added_user,@skill)
      flash[:notice] = @skill.name + " に +1 しました"
    else
      flash[:alert] = @skill.name + " への +1 に失敗しました"
    end

    return redirect_to added_user
  end

  def destroy
  end

  private

    def skill_params
      params.require(:skill).permit(:name)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/user_lists_controller.rb
class UserListsController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    _skills, @counts = @user.skills_list
    @skills = _skills.paginate(page: params[:page])
    @new_skill = Skill.new
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
    count: resource.errors.count,
    resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h5>#{sentence}</h5>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
  
  # ページごとの完全なタイトルを返す
  def full_title(page_title = '')
    base_title = "インターンシップ課題プログラム"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/me_helper.rb
module MeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_lists_helper.rb
module UserListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "internship app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      	<li><%= link_to current_user.name, user_path(current_user) %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Settings", edit_me_path %></li>
        <li><%= link_to "Logout", me_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign up", new_user_path %></li>
        <li><%= link_to "Login", new_me_session_path %></li>
      <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shims.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
	  <%= render 'layouts/shims' %>
  </head>
  <body>
	  <%= render 'layouts/header' %>
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <p><%= notice %></p>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <p><%= alert %></p>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
  <%= debug(params) if Rails.env.development? %>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_skill_form.html.erb
<%= form_for(@new_skill) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div><%= hidden_field_tag :added_id, @user.id %></div>
  <div class="field">
    <%= f.text_area :name, placeholder: "新しいスキルを追加する" %>
  </div>
  <%= f.submit "新しいスキルを追加する", class: "btn btn-primary" %>
<% end %>

app/views/skills/_skill.html.erb
<li id="skill-<%= skill.id %>">
  <div class="row">
  <span class="col-md-1">
    <span class="count"><%= counts[skill.id] %></span>
  </span>
  <span class="col-md-9">
    <span class="name"><%= skill.name %></span>
  </span>
  <span class="col-md-2">
    <%= render 'plus_form', skill: skill %>
  </span>
  </div>
</li>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
<h2>ログイン済み</h2>
<% else %>
<div class="center jumbotron">

  <h2>
    インターンシップの課題プログラムのページです。
  </h2>

  <%= link_to "Sign up", new_user_path, class: "btn btn-lg btn-primary" %>
</div>
<% end %>

app/views/user_lists/_plus_form.html.erb
<% if current_user.plussed?(@user, skill) %>
  <%= form_for(current_user.add_skill.find_by(user_id: @user.id, skill_id: skill.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "-1", class: "btn" %>
  <% end %>
<% else %>
  <%= form_for(current_user.add_skill.build) do |f| %>
    <div><%= hidden_field_tag :skill_id, skill.id %></div>
    <div><%= hidden_field_tag :user_id, @user.id %></div>
    <%= f.submit "+1", class: "btn btn-primary btn-large" %>
  <% end %>
<% end %>

app/views/user_lists/_skill_form.html.erb
<%= form_for(@new_skill) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div><%= hidden_field_tag :added_id, @user.id %></div>
  <div class="field">
    <%= f.text_area :name, placeholder: "新しいスキルを追加する" %>
  </div>
  <%= f.submit "新しいスキルを追加する", class: "btn btn-primary" %>
<% end %>

app/views/user_lists/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/user_lists/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate @users %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate @users %>

app/views/user_lists/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
  <section class="skill_form">
    <%= render 'skill_form' %>
  </section>
    <% if @user.skills.any? %>
      <h3>Skills</h3>
      <ol class="skills">
        <%= render @skills, counts: @counts %>
      </ol>
      <%= will_paginate @skills %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>